### ISSUE TITLE
Tried and failed

### ISSUE THREAD

**Issue by leobragaz** [elliptic-email/rust-grpc-web#1]
Hi @ianpurton. I saw your comment [here](https://github.com/hyperium/tonic/issues/31) and I couldn't resist to try out your code since it was weeks that I was searching around for something like this. Great work!

As the title said, I tried it and generated [this code](https://github.com/forbole/cosmos-rust/blob/grpc-web-clients-generation/cosmos-sdk-proto/src/prost/cosmos.auth.v1beta1.rs) which is part of a bigger library that I'm using and trying to make it compile to WASM. Unfortunately for me, when I tried to build it with `wasm-pack build` it failed with the errors coming from `socket2` which after a `cargo tree` I discovered to be part of `hyper` of `reqwest. 
I saw that `reqwest` is used to generate the client and as you stated in the issue's comment, you used it to make it compile to WASM. I can't understand why my code still don't compile at it even though it looks like it should.
What am I missing here?
Thanks in advance for your answer.

**Comment by leobragaz** [comment]
I'm sorry, it was my fault. There was a default feature that was linked with tonic.

**Comment by ianpurton** [comment]
@bragaz Glad you got it working.
